<script setup>
const emit = defineEmits(['home', 'portfolio'])

const episodes = [
  { title: 'A história e os bastidores de quem constrói o futuro do morar.', label: 'Episódio 01', url: 'https://www.youtube.com/watch?v=Pz9RMYf7MlM' },
  { title: 'Identidade, território e a coragem de criar referências.', label: 'Episódio 02', url: 'https://www.youtube.com/watch?v=7abUzGii3iU' },
  { title: 'Pessoas, propósito e o legado de cada entrega.', label: 'Episódio 03', url: 'https://www.youtube.com/watch?v=DMyp2arEY5o' }
]
</script>

<template>
  <main class="about-page">
    <section class="about-hero section-dark"><div class="shell about-hero-inner"><a class="back-link light" href="/" @click.prevent="emit('home')">← Voltar para a Home</a><div class="about-hero-copy"><div class="section-kicker light"><span></span> Sobre nós</div><h1>+28 anos construindo<br /><em>o futuro do morar.</em></h1><p>Desde 1998, a Bauten transforma paisagens urbanas no Nordeste com projetos que unem arquitetura autoral, inovação construtiva e compromisso com as pessoas.</p></div></div></section>
    <section class="section shell about-history"><div class="section-heading"><div><div class="section-kicker"><span></span> Nossa história</div><h2>Uma trajetória<br /><em>em movimento.</em></h2></div></div><div class="about-timeline"><div><strong>1998</strong><span>Fundação da Bauten em João Pessoa</span></div><div><strong>2005</strong><span>Expansão para Recife e Natal</span></div><div><strong>2012</strong><span>Primeiro empreendimento com certificação sustentável</span></div><div><strong>2018</strong><span>Marco de 1.500 unidades entregues</span></div><div><strong>2022</strong><span>Lançamento do conceito senior living com o Arcos</span></div><div><strong>2024</strong><span>Parceria inédita com L’Occitane para o Tekoá</span></div><div><strong>2026</strong><span>+2.800 unidades entregues e 6 empreendimentos ativos</span></div></div></section>
    <section class="section shell about-pillars"><div class="section-heading"><div><div class="section-kicker"><span></span> O nosso método</div><h2>Intenção em<br /><em>cada detalhe.</em></h2></div><p>Os pilares orientam cada decisão da Bauten, da concepção do projeto à entrega e à relação com as pessoas.</p></div><div class="about-pillar-list"><div class="method-item"><b>01</b><div><h3>Responsabilidade social e ambiental</h3><p>Compromisso com o meio ambiente, a comunidade, a arte e o bem-estar coletivo.</p></div><span>↗</span></div><div class="method-item"><b>02</b><div><h3>Excelência e disciplina</h3><p>Qualidade, eficiência e rigor em todos os processos.</p></div><span>↗</span></div><div class="method-item"><b>03</b><div><h3>Aprendizado e inovação</h3><p>Evolução contínua de pessoas, processos e soluções.</p></div><span>↗</span></div><div class="method-item"><b>04</b><div><h3>Igualdade e respeito</h3><p>Ambiente justo, inclusivo e colaborativo.</p></div><span>↗</span></div><div class="method-item"><b>05</b><div><h3>Transparência e ética</h3><p>Clareza, integridade e relações de confiança.</p></div><span>↗</span></div></div></section>
    <section class="about-video-feature section-dark"><div class="shell about-video-grid"><div><div class="section-kicker light"><span></span> Bauten no YouTube</div><h2>Uma história construída<br /><em>em movimento.</em></h2><p>Conheça os bastidores, as pessoas e as ideias que dão forma a cada projeto Bauten.</p><a class="button button-light" href="https://www.youtube.com/@bautenbrasil" target="_blank" rel="noreferrer">Acessar o canal <span>↗</span></a></div><div class="about-video-screen"><iframe src="https://www.youtube.com/embed/1KSaC8P3PYI?rel=0&modestbranding=1" title="Vídeo Institucional Bauten" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div></div><div class="shell about-episodes"><a v-for="episode in episodes" :key="episode.label" class="about-episode" :href="episode.url" target="_blank" rel="noreferrer"><span>{{ episode.label }}</span><h3>{{ episode.title }}</h3><b>Assistir no YouTube ↗</b></a></div></section>
    <section class="section shell about-leadership"><div class="section-heading"><div><div class="section-kicker"><span></span> Liderança</div><h2>Por trás de<br /><em>cada decisão.</em></h2></div><p>Uma empresa conduzida por pessoas que unem sensibilidade, rigor técnico e visão de crescimento.</p></div><div class="leaders"><article><img src="https://bauten.cc/assets/meiry-BbqGsf1e.png" alt="Meiry França, fundadora e CEO da Bauten" loading="lazy" /><div><span>Fundadora & CEO</span><h3>Meiry França</h3><p>Engenheira Civil com mais de 28 anos liderando projetos que redefinem o morar no Nordeste. Sua visão une sensibilidade estética com rigor técnico.</p></div></article><article><img src="https://bauten.cc/assets/esau-Du89lpO0.png" alt="Esaú Magalhães, cofundador da Bauten" loading="lazy" /><div><span>Co-fundador & Diretor de Novos Negócios</span><h3>Esaú Magalhães</h3><p>Mais de 20 anos em gestão financeira, fundos de investimento e estruturação de negócios imobiliários. Responsável pela estratégia de crescimento da Bauten.</p></div></article></div></section>
    <section class="section-tint about-location"><div class="shell about-location-grid"><div><div class="section-kicker"><span></span> Onde estamos</div><h2>Uma presença<br /><em>perto de você.</em></h2><p>Nosso escritório está em João Pessoa, onde seguimos construindo relações duradouras e novos capítulos para a cidade.</p><a class="button button-dark" href="https://www.google.com/maps/search/?api=1&query=R.+Hildebrando+Tourinho,+40,+Miramar,+Jo%C3%A3o+Pessoa,+PB,+58032-080" target="_blank" rel="noreferrer">Ver localização no Google Maps <span>↗</span></a></div><div class="about-location-map"><iframe src="https://www.google.com/maps?q=R.+Hildebrando+Tourinho,+40,+Miramar,+Jo%C3%A3o+Pessoa,+PB,+58032-080&output=embed" title="Localização do escritório Bauten em João Pessoa" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></div></section>
  </main>
</template>
